### ISSUE TITLE
$('#filterid').trigger('keyup') is not working (not refreshing filter)

### ISSUE THREAD

**Issue by ghost** [PicNet/tablefilter#15]

**Comment by henla464** [comment]
Instead of using JQuery to trigger the refresh, use closures goog.testing.events.fireKeySequence(...).

**Comment by henrikl** [comment]
There is now a refresh function that can be used to trigger filtering. 
You can call the refresh function like this (if the table you created filter for has id=demotable): 

$('#demotable').tableFilterRefresh();

Also see the included demo examples.
