### ISSUE TITLE
tableFilter adds the filter fields but they don't do anything

### ISSUE THREAD

**Issue by anentropic** [PicNet/tablefilter#16]
I do:

```
$(document).ready(function() {
    $('#teamlist').tableFilter({
        enableCookies: false,
        matchingCell: function(state, td, textTokens) {
            console.log(state, td, textTokens);
            return false;
        },
        filteringRows: function(filterStates) {
            console.log(filterStates);
        }
    });
});
```

...and the filter drop-downs are added to my specified fields in the table.

But when I choose an option nothing happens. I would expect to see something in the console from one of the functions at least but it looks like no event is triggered.

Unfortunately because it's all built with Google Closure I can't easily add in some debugging code of my own. Do you have any ideas why it might not work?

**Comment by anentropic** [comment]
if I call

```
$('#teamlist').tableFilterRefresh();
```

from the Firebug console it works, so it's just that the on change handler isn't working...

I assumed I didn't need to manually attach those to the generated select lists?

**Comment by anentropic** [comment]
if I do

```
$('#teamlist tr.filters select.filter').change(function(e){
    $('#teamlist').tableFilterRefresh();
})
```

then everything works...

**Comment by henla464** [comment]
Not sure what happens, could you make your table public so I can test it?

Is both the text filters and the dropdown filters broken when you use the keyboard to type/mouse to select? (they will not trigger if you set values with JQuery)

**Comment by anentropic** [comment]
hi sorry, yes it'd be helpful if I made a test case for you

I wasn't using text fields in the table, it was drop-down lists.  the drop-downs don't trigger any filtering events when using the mouse.  I didn't have any code to set the drop-down values from js.

**Comment by henla464** [comment]
It would be helpful. If you do prepare something, please do it with the tableFilter javascript that isn't minified/compiles. That will make it easier to debug.

Do you do anything different than it is done the demo example here? http://www.picnet.com.au/resources/tablefilter/demo.htm

**Comment by henrikl** [comment]
Hello, 
The compiled/minified version was broken but a new version is now committed and it should work. I'm closing this issue (open a new issue if the new version doesn't solve your issue).
