### ISSUE TITLE
matchingCell never gets called

### ISSUE THREAD

**Issue by anentropic** [PicNet/tablefilter#17]
```
$('.tablefilter').tableFilter({
    enableCookies: false,
    selectOptionLabel: 'Filter by...',
    matchingCell: function(state, td, textTokens) {
        console.log(textTokens);
        return false;
    }
});
```

nothing is logged to console when filtering

the equivalent using matchingRow does work

is there some other requirement or trick to ensure matchingCell is called?

**Comment by gatapia** [comment]
No trick, must be a bug.  Tnx will be looked into asap

**Comment by henrikl** [comment]
Hi, I have now looked into this... "matchingCell" isn't called anywhere in the code. Perhaps it was used at some point and the documentation wasn't updated when it was removed. I have removed the references in the documentation to this method. I hope you will find another way to archive what you are trying to do.
