### ISSUE TITLE
Filter fails when new data added to table

### ISSUE THREAD

**Issue by oasis2pa** [PicNet/tablefilter#18]
I'm using an Ajax request to replace information (meaning rows, <tr></tr>) on a table...however, the tableFilter() function does not respond to the new rows. Is there maybe a way to destroy it and reinitialize?  If I leave the old data and append the new data....the old data still gets filtered, but not the new data. For the most part, all old rows will be removed completely and new rows added. How do I reinitialize the function to allow for recognition of the new information?

I have tried certain events/functions like .die(), .unbind() , 'destroy', etc....but none of them had the desired effect.

**Comment by gatapia** [comment]
HI, try using .refresh() when the new data is available.

**Comment by oasis2pa** [comment]
Sadly, it would not work. I ended up writing my own table filters that works on all rows, whether original or dynamic.  For some reason the picnet filter could not recognize the newly generated rows from an ajax request. I may have just been missing something, but my filter works fine for now. Thank you

**Comment by 17seconds** [comment]
I'm facing the same issue, working with live data and Ajax. I've try the refresh method after the load of the new data but it's does not respond. Is there some news from this side or what solution can be use ? By the way, thanx for this great plug in and all the work  it require.

**Comment by henrikl** [comment]
We have made some changes... the tableFilterRefresh method should now fix your issue. The previous functionality of tableFilterRefresh is now called tableFilterApplyFilterValues. I'm closing this issue, reopen if you still have problem with this.
