### ISSUE TITLE
Demo js file does not work

### ISSUE THREAD

**Issue by ghost** [PicNet/tablefilter#19]
Hi,

In the demo that is downloadable from your site, the js attached is not working, the filters aren't trigger ed when you enter something in the text-fields, nor the drop-down. But replacing the js with a separately downloaded file solves it, so something fishy in the one included.

Otherwise, great script!

**Comment by gatapia** [comment]
Thanks for the report.  I'll get that fixed up first thing tomorrow morn.

**Comment by henrikl** [comment]
Hi, 
This is now fixed, thanks.

**Comment by ghost** [comment]
That's splendid! :)
