### ISSUE TITLE
Current version number?

### ISSUE THREAD

**Issue by eddywashere** [PicNet/tablefilter#25]
Last one I could find was 2.0.1 back in Feb of 2010: http://plugins.jquery.com/node/10444/release

**Comment by gatapia** [comment]
I had totally forgot about the jQuery plugins page.  Will update it today.

In the meantime please take the github version.

Thanks for the heads up

**Comment by henla464** [comment]
The plugins page has now been updated. Thanks for reporting. I suggest though that you use the version from github since it will always be the latest.

Thanks!

**Comment by eddywashere** [comment]
Awesome and will do. Thanks!
