### ISSUE TITLE
Numeric expressions do not work properly with decimals

### ISSUE THREAD

**Issue by psybertech** [PicNet/tablefilter#26]
Great plugin!

Issue I have is that if you a column with decimals, the > < do not work correctly.

Example 1:
filter is >3
values are:
3.1
3.5
3.9
4
will only show the '4'
it will not show the  3.x values

Example 2:
filter is >3.1
3.1
3.5
3.9
4
yields no results

Anything I can do to make this work with decimals?

Thanks!

**Comment by henla464** [comment]
Hi,

Please test the new release uploaded a few minutes ago. It has a fix for this.

Cheers
Henrik

**Comment by psybertech** [comment]
PERFECT!

Thank you!

cheers
