### ISSUE TITLE
Filtering Columns with "Thousands Separator" fails

### ISSUE THREAD

**Issue by jquerynewbie** [PicNet/tablefilter#28]
Hello,

filtering Columns, which include numbers with a thousands separator fails.
e.g. 1.000 or 2.500

Only filtering with numbers without a separator works
eg 1000 or 2500

In my columns, there have to be thousands separators. And I want to make filtering with PicNet works properly.

I think it's just a small change on the code. When table filter is reading the contents of the columns, the thousands separator has to be replaced.

 .replace (".","")
But the code is so complex, I don't know where (on which variable) I have to add the replacement command.

I hope you can help me or give me just a hind.

Thank you very much!

**Comment by henrikl** [comment]
Hi,

I'm on vacation so can't have a look at this right now. But if you look in the SearchEngine.js there should be code that handles number comparisons. I'm not sure exactly what the problem you are having is. Is it normal filtering or comparison (for example  > 1000 )? If it is comparison then look for parseFloat or parseInt in the SearchEngine.js file (was recently changed to parseFloat from parseInt so depends on which version you are using).

Thanks
Henrik

Henrik Larsson | Senior Software Developer | PicNet________________________________________
From: jquerynewbie [reply@reply.github.com]
Sent: Friday, 11 November 2011 12:58 AM
To: Henrik Larsson
Subject: [tablefilter] Filtering Columns with "Thousands Separator" fails (#28)

Hello,

filtering Columns, which include numbers with a thousands separator fails.
e.g. 1.000 or 2.500

Only filtering with numbers without a separator works
eg 1000 or 2500

In my columns, there have to be thousands separators. And I want to make filtering with PicNet works properly.

I think it's just a small change on the code. When table filter is reading the contents of the columns, the thousands separator has to be replaced.

 .replace (".","")
But the code is so complex, I don't know where (on which variable) I have to add the replacement command.

I hope you can help me or give me just a hind.

Thank you very much!

---

Reply to this email directly or view it on GitHub:
https://github.com/PicNet/tablefilter/issues/28

**Comment by jquerynewbie** [comment]
Hey, 

First of all thank you for your answer! Especially in your vacation.

I did not express myself well. 
<b>EDIT 14.11.2011</b>
<b>I want to get (for example) >1000 work, as well my columns contain numbers with thousands separators (1.000, 2.000, 3.000 but also 200, 300, 100)</b> For this columns comparison does not work properly.

So I think this has nothing to do with the SearchEngine.js.
I have looked in to the SearchEngine section in the picnet.table.filter.min.js, but if the section with the parseFloat commands deals with the field, where you can type in the filtering / comparison. For example >1000.

But I have to change the variable, where the columns values are read in (or stored). (1.000, 2.000, 3.000). 
But I don't know, where I can find this variable to replace the "."

What I have not understood:
What does the different Files in this directory on this page mean (tablefilter / src / picnet / ui / filter)?
<i>Is the picnet.table.filter.js a special buildup of all these files? (I looked into the files but could not find a 100% match with the picnet.table.filter.js)</i>

At the moment I am using the following code in my header to include the TableFilter (for sure without the """""):
<i><""""""""script type="text/javascript" src="Scripts/jquery-1.4.2.min.js"></script->
<""""""""script type="text/javascript" src="Scripts/picnet.table.filter.js"></script-></i>

Thank you very much for helping me.

**Comment by henla464** [comment]
Hi,

The values in the table rows are read in GenericListFilter.js, function doesTextContainText. Search for goog.dom.getTextContent(item). This is used for all columns so if you only want to do the replace on certain columns I'm not sure how to do that...

The picnet.table.filter.min.js is a "compiled"/minified version created from the source files using the closure compiler (see compile.bat). If you don't want to compile/minify then you can use the source files as is done in demosrc.htm (easier to develop and debug in the browser).

**Comment by jquerynewbie** [comment]
Hey,

Thank you very much for your answer. It helps me alot. 
I don't think, that it will be a problem to do the replace on all columns (for my table).

So for now I will try to get it work.

Thank you again.

**Comment by jquerynewbie** [comment]
Hello again,

I <b>solved</b> the problem:
Original Line in GenericListFilter.js (442)
return this.doesTextContainTextImpl(goog.string.trim(goog.dom.getTextContent(item)), textTokens, exact); 

Modified line to make "." as thousands separator work:
return this.doesTextContainTextImpl(goog.string.trim(goog.dom.getTextContent(item)<b>.replace('.','')</b>), textTokens, exact); 

Thank you all very much for your help!
