### ISSUE TITLE
Issue with IE and filter-type='ddl'

### ISSUE THREAD

**Issue by ghost** [PicNet/tablefilter#3]
it seems there an issue with IE with filter-type='ddl'. It doesn't work (test with IE8). I'm using the script on a page of my wordpress website (http://www.planete-android.com/comparateur/) with inline-javascript plugin (to put the script). Sometimes, i get the error res://ieframe.dll/acr_error.htm#planete-android.com,http://www.planete-android.com/comparateur/. The function filter-type='ddl' doesn't work too with the demo page (demo.htm).

Comments
pandreid wrote Aug 26 2010 at 6:24 AM
I tried demo.htm with the last version (54318). It's ok with stable version (release.zip). Aniway, it seems it's a wordpress/plugin/jquery issue.. Thanks.

gatapia wrote Aug 23 2010 at 9:50 AM
I tried this (on demo.htm) in IE7 and 8 and it works fine with both versions. I tried to access your website but it would crash my browser so I could not test.

**Comment by PicNet** [comment]
Since you seem to have found a solution this issue will be closed, if you don't object
