### ISSUE TITLE
picnetcompiler.jar is missing

### ISSUE THREAD

**Issue by ghost** [PicNet/tablefilter#31]
There is no longer any lib directory, which means that there is no longer a picnetcompiler.jar. The README does not address where it went or where to find it. I downloaded it from an old revision, but needless to say, it was very confusing.

**Comment by gatapia** [comment]
I'll get the readme updated today guys, forgot all about it when I removed
those 30MB+ of shared libs out of the project.

On Thu, Dec 8, 2011 at 6:29 AM, mechaxl <
reply@reply.github.com

**Comment by gatapia** [comment]
This is fixed in commit eba9e723fb2139813174aafa0f181d94da029aa3.

I would appreciate a review of the readme file just to make sure it is understandable.  Setting up closure compiler/library is notoriously hard so hopefully I've made it easy enough.  Let me know if not.
