### ISSUE TITLE
Unable to refresh new table data

### ISSUE THREAD

**Issue by ghost** [PicNet/tablefilter#32]
Hi,

at first: thanks for the great plugin and a lot of respect for your work!

Unfortunately it's not possible to refresh tablefilter after new data were
added to the table or if the table was completly replaced after a ajax request.

It would be very great if you could implement this feature, because it's a bit
strange that it's only possible to work with static data.

At the moment I am using quicksearch (https://github.com/riklomas/quicksearch)
that provides a cache() function to refresh the cached table data.

Cheers,
Jonny

**Comment by ghost** [comment]
Hello again.

Do you think that you implement this feature?

I look forward to your reply.

Cheers,
Jonny

**Comment by henla464** [comment]
Hi,

A new .tableFilterReset() function has been added. This function repopulates the internal cache of rows. Calling this after the table has been replaces should solve your problem.

**Comment by henrikl** [comment]
Since the naming of the tableFilterRefresh and tableFilterReset functions were a bit misleading they have been renamed.
They are now called:

tableFilterApplyFilterValues (previously tableFilterRefresh)
and
tableFilterRefresh (refreshes the cache of data)

**Comment by ghost** [comment]
Yeah! Great! I will test it! Big thanks!

Where can I donate?
