### ISSUE TITLE
Duplicated id attributes

### ISSUE THREAD

**Issue by pepebe** [PicNet/tablefilter#33]
...if multiple tables are filtered with tablefilter

Each filtered table on a page will have #filter_1, #filter_2 and so on. 

Edit: This will result in duplicate ID attributes which is a bad thing for obvious reasons...

So far I haven't encountered any problems with this behavior, but I can imagine that this might cause problems in some contexts.

Regards,

pepebe

BTW: What is the proper place to ask some questions regarding usage of the script?

**Comment by henrikl** [comment]
Thanks for reporting this. I actually encountered an issue with this and it has now been fixed. The id now uses the id of the table to prefix the filter id's.
