### ISSUE TITLE
after removing filter complete list of table is not visible

### ISSUE THREAD

**Issue by manashgarg** [PicNet/tablefilter#36]
in any txt search coulm if i type somethein and erase it the comple list of table does not re populate.

Please help:  the error is

$header$$5$$ is undefined
$$JSCompiler_prototypeAlias$$$$doesElementContainText$$()picnet....min.js (line 167)
$JSCompiler_StaticMethods_applyStateToElements$$()picnet....min.js (line 123)
$JSCompiler_StaticMethods_applyFilterStatesImpl$$()picnet....min.js (line 119)
$JSCompiler_StaticMethods_applyFilterStates$$()picnet....min.js (line 116)
$$JSCompiler_prototypeAlias$$$refresh$()picnet....min.js (line 111)
$$JSCompiler_prototypeAlias$$$$quickFindTimer$$()picnet....min.js (line 110)
anonymous()picnet....min.js (line 110)
anonymous()picnet....min.js (line 6)
[Break On This Error] $JSCompiler_prototypeAlias$$.$doesElem...$header$$5$$.getAttribute("filter")&&

**Comment by midium** [comment]
I'm having the same issue too.

Uncaught TypeError: Cannot read property 'style' of undefined
$$JSCompiler_prototypeAlias$$$$doesElementContainText$$picnet.table.filter.min.js:174
$JSCompiler_StaticMethods_applyStateToElements$$picnet.table.filter.min.js:129
$JSCompiler_StaticMethods_applyFilterStatesImpl$$picnet.table.filter.min.js:124
$JSCompiler_StaticMethods_applyFilterStates$$picnet.table.filter.min.js:122
$$JSCompiler_prototypeAlias$$$refresh$picnet.table.filter.min.js:115
$$JSCompiler_prototypeAlias$$$$quickFindTimer$$picnet.table.filter.min.js:114
(anonymous function)

**Comment by henla464** [comment]
Hi,

I have tried to reproduce this problem but haven't been able to. Can it be reproduced with demo.htm or demoSrc.htm? Does it happen in all browsers or only a specific one?

**Comment by midium** [comment]
Hi,
I have understand when the issue rise.
I was trying to reproduce it for you and I've seen this.
Suppose we have a table with 4 columns. If I set an header for each column then the filter works properly, but when I remove an header (suppose last column is used just for an edit link and I don't want to let it be filtered) then the issue raise.

I hope I've been able to explain myself

**Comment by henla464** [comment]
You will need to use the same number of header cell (th) as row cells (td). If you just add an empty th cell it shouldn't create a filter control for it. Let me know if that solves your problem.

**Comment by midium** [comment]
Yes, that solve the issue but I need to leave the last column without the header as I don't want to filter on it.
I mean my table has some data in the first 5 columns and the last 2 has an edit and delete link.
So I just want to filter on the first 5 columns as the last 2 are always "Edit" or "Delete".

**Comment by henla464** [comment]
Did you try with an empty th? If so, does it really create a filter control for that column?

**Comment by midium** [comment]
Great, that seems to work! Thanks

**Comment by henla464** [comment]
midium: Great! 
There is also another way to turn off filtering without using an empty header cell:
&lt;th filter="false"&gt;column name&lt;/th&gt;

manashgarg: I'm guessing your problem is slightly different. Are you using a header row for your table at all?
