### ISSUE TITLE
Uncaught TypeError: Cannot call method 'appendChild' of undefined

### ISSUE THREAD

**Issue by marceloverdijk** [PicNet/tablefilter#38]
I tried the tableFilter for the first time but got:
Uncaught TypeError: Cannot call method 'appendChild' of undefined

My code:

`````` <p>
    <input id="test-filter" type="text" class="search-query" placeholder="Zoeken">
</p>
<table id="test-list" class="table table-striped">
    <tbody>
        <tr>
            <td>Marcel Overdijk</td>
        </tr>
    </tobdy>
</table>```

and

```$(document).ready ->
    $('#test-list').tableFilter({
        additionalFilterTriggers: [$('#test-filter')]
    })```


I'm using latest jQuery 1.7.1.

Any idea what I'm doing wrong here?
``````

**Comment by henla464** [comment]
Hi Marcel,

You need to add a table header row to your table, something like this:

<table id="test-list" class="table table-striped">
<thead>
          <tr><th>Text Column 1</th></tr>
</thead>
<tbody>
  <tr>
     <td>Marcel Overdijk</td>
  </tr>
</tobdy>
</table>

**Comment by marceloverdijk** [comment]
Thanks! That was better but now I get a: Uncaught TypeError: Cannot read property 'style' of undefined

BTW, per my design I can't add headers. Is there no option to use tableFilter without headers?

I'm looking to implement something similar to: http://jquerymobile.com/test/docs/lists/lists-search.html

**Comment by henla464** [comment]
Hi Marcel!

Try the latest version, it creates the header row automatically if it is missing. See demosrc2.hml for an example. Since you probably don't want to show the header, just hide it with CSS.
