### ISSUE TITLE
no filter is created for column when header text is only one character long

### ISSUE THREAD

**Issue by vlandham** [PicNet/tablefilter#39]
Not sure if this is expected behavior. If a column header is something like 'X', 'y', or 'r', no filter is created for it. 

In the current version of picnet.table.filter.full.js - line 15960:

https://github.com/PicNet/tablefilter/blob/master/picnet.table.filter.full.js#L15960

has:

<pre>
        if (headerText && headerText.length > 1) {
            var filter = this.getFilterDom(i, header);
            goog.style.setStyle(filter, 'width', '95%');
            td = goog.dom.createDom('td', null, filter);                                                
        } else { td = goog.dom.createDom('td', {}, ''); }           
</pre>

I believe this is the source of the issue. Is there a reason that headerText.length cannot be >= 1 ?

**Comment by henrikl** [comment]
Hi,

I don't believe there is a reason, it probably should be > 0. I will do some testing...

**Comment by henrikl** [comment]
I have changed it to check for > 0 instead. If anyone notices any problem with this let us know.

**Comment by vlandham** [comment]
awesome. thank you!
