### ISSUE TITLE
Column with select elements

### ISSUE THREAD

**Issue by kbirk-zz** [PicNet/tablefilter#42]
Hi
Iam using this plugin, and needs filtering on a column with select elements. The filter should use the selected option. Is there a buildin solution for this?

/Kasper

**Comment by tallen007** [comment]
on your table column heading put the attribute "filter-type='ddl'"
example:
<th filter-type='ddl' >Data Type</th>

**Comment by kbirk-zz** [comment]
Does it work when the data is a select element? I tried bit the filter ddl only had option element where all data for the column was mixid in. I will make an example next week.
