### ISSUE TITLE
tableFilterRefresh() not updating options for DDL filtered column

### ISSUE THREAD

**Issue by DiogoAndre** [PicNet/tablefilter#43]
Select options are not updated after calling tableFilterRefresh() on a table with DDL filtered column.

**Comment by henrikl** [comment]
G'day,

Thanks for reporting this issue, I'm happy to announce that this issue was fixed earlier today. The code here on github contains the fix.

Kind Regards,
Henrik Larsson

**Comment by DiogoAndre** [comment]
Thanks!
