### ISSUE TITLE
Add refresh() to the table filter

### ISSUE THREAD

**Issue by ghost** [PicNet/tablefilter#5]
Ideal for Ajax tables.

**Comment by tmuth** [comment]
We exchanged an email on this and you mentioned it's implemented in google closure but not in jQuery. I have no experience with google closure and honestly have no idea where to start (sorry).

**Comment by henrikl** [comment]
There is now a refresh function that can be used to trigger filtering. 
You can call the refresh function like this (if the table you created filter for has id=demotable): 

$('#demotable').tableFilterRefresh();

Also see the included demo examples.

**Comment by tmuth** [comment]
Perfect! I just tested this in my chrome extension and it works perfectly. I can now eliminate a bunch of code and a poor UI hack I used to pseudo-implement this functionality.
