### ISSUE TITLE
JS to Clear Filters

### ISSUE THREAD

**Issue by kameelyan** [PicNet/tablefilter#60]
I didn't see a way via a JS call to tell tableFilter to clear all filters, so I went ahead and added one:

I added the following code to the jQuery portion of the plugin:

This code goes inside the jq.tableFilter function:

```
        plugin.clearFilters = function () {
            pn.ui.filter.TableFilter.superClass_.clearAllFilters.call(tf);
        };
```

This code I added below the other defined functions

```
    jq['fn']['tableFilterClearFilters'] = function (options) {
        var tmp = goog.array.forEach(this, function (t) {
            if (undefined !== jq(t).data('tableFilter') &&
        jq(t).data('tableFilter') !== null) {
                var plugin = jq(t).data('tableFilter');
                plugin.clearFilters(t);
            }
        });
        return tmp;
    };
```

Just wanted to share in case others needed this functionality.

**Comment by gatapia** [comment]
Added to latest commit, thanks for that
